/* tslint:disable */
/* eslint-disable */
/**
 * Chat API
 * API for southball/next-chat.
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountUpdate
 */
export interface AccountUpdate {
    /**
     * 
     * @type {string}
     * @memberof AccountUpdate
     */
    userGuid: string;
    /**
     * 
     * @type {string}
     * @memberof AccountUpdate
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountUpdate
     */
    displayName?: string;
}

export function AccountUpdateFromJSON(json: any): AccountUpdate {
    return AccountUpdateFromJSONTyped(json, false);
}

export function AccountUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userGuid': json['user_guid'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
    };
}

export function AccountUpdateToJSON(value?: AccountUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_guid': value.userGuid,
        'username': value.username,
        'display_name': value.displayName,
    };
}

