/* tslint:disable */
/* eslint-disable */
/**
 * Chat API
 * API for southball/next-chat.
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface ChatMetadata
 */
export interface ChatMetadata {
    /**
     * 
     * @type {string}
     * @memberof ChatMetadata
     */
    chatGuid?: string;
    /**
     * 
     * @type {User}
     * @memberof ChatMetadata
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof ChatMetadata
     */
    latestMessage: string;
}

export function ChatMetadataFromJSON(json: any): ChatMetadata {
    return ChatMetadataFromJSONTyped(json, false);
}

export function ChatMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chatGuid': !exists(json, 'chat_guid') ? undefined : json['chat_guid'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
        'latestMessage': json['latest_message'],
    };
}

export function ChatMetadataToJSON(value?: ChatMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chat_guid': value.chatGuid,
        'user': UserToJSON(value.user),
        'latest_message': value.latestMessage,
    };
}

