[package]
edition = "2021"
name = "next-chat-server"
version = "0.1.0"

[dependencies]
actix-cors = "0.6.0-beta.10"
actix-web = "4.0.0-rc.3"
anyhow = "1.0.53"
dotenv = "0.15.0"
lazy_static = "1.4.0"
regex = "1.5.4"
serde = "1.0.136"
sqlx = {version = "0.5.10", features = ["runtime-tokio-native-tls", "postgres"]}
tokio = {version = "1.16.1", features = ["full"]}
